services:
  api:
    image: atomflow/api:internal-20260507

  worker:
    image: atomflow/api:internal-20260507

  worker_beat:
    image: atomflow/api:internal-20260507

  web:
    image: atomflow/web:internal-20260507
